spring:
  application:
    name: trade-admin
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 0
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
#mybatis config
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

ribbon:
  http:
    client:
      enabled: true
  ReadTimeout: 11000
  ConnectTimeout: 11000
#port
server:
  port: 8080
#eureka client config
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8077/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html